### PR TITLE
Improvement/Front end- User registration

### PR DESCRIPTION
**Pull request by goflyy**
image
Dear co-creators of the APPLICATION FOR STUDIES! HERE'S AHEAD!! NEW! READABLE! TRANSPARENT! User panel gui.

### CODE REVIEW

**Comment by Cialkowski** [comment]
add label, add project, add revierews. Add screenshot and description

**Review by Cialkowski — CHANGES_REQUESTED** [review]
update branch. You must not merge changes from 'behind' branch.

**Comment by Borzygniew** [comment]
add screenshot of how it looks like now

**Comment by goflyy** [comment]
> add label, add project, add revierews. Add screenshot and description
 Done :)

**Comment by goflyy** [comment]
> add screenshot of how it looks like now

**Review by Borzygniew — DISMISSED** [review]
👺

**Review by Cialkowski — CHANGES_REQUESTED** [review]
Pull has to be done from develop branch, because after Kacper's changes your changes would be pushed 2 times and it makes no sense. Kacper changed base branch to develop again. Update your current branch as I said first time and it will be merged. It is better solution

**Review by Borzygniew — APPROVED** [review]
lgtm 😁

**Pull request merged**
